#!/bin/python3

import math
import os
import random
import re
import sys

def birthdayCakeCandles(candles):
    # Write your code here
    max_height = max(candles)      #max yükseklik tutmalıyız çünkü mum listesindeki en uzun mumlara ihtiyacımız var 
    
    count = 0                      #burada bir count değeri tutuyoruz ki uzun mum sayısını burada artıralım. 
    for candle in candles:         #candle candles listesinde olduğunda 
        if candle == max_height:   #eğer mumun uzunluğu en uzun mum yüksekliğine eşitse countu bir arttıralım 
            count += 1
    return count                   #count değerini döndürelim
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()
